<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
    <a class="navbar-brand" href="#">pogchamp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="add.php">Add</a>
        <a class="nav-item nav-link" href="view.php">Products <span class="sr-only"></span></a>
         <a class="nav-item nav-link" href="salesReport.php">Sales Reports</a>
         <a class="nav-item nav-link" href="viewTransactions.php">Transactions</a>
      </div>
      <div class="navbar-nav ml-auto">
      <?php
          if(isset($_SESSION['login_user']))
          {
              echo '<a class="nav-item nav-link" href="login.php">Log In</a>';
          }
          else
          {
              echo '<a class="nav-item nav-link" href="login.php">Log Out</a>';
          }
      ?>
      </div>
    </div>
     </div>
  </nav>
</header>
